[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_twitter = "FCChUjoAnEeFT4WzMgQLn2dBcXwYnL6XQkj5NumGF6AE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sanjeet/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
